# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-13 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190813_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Perm_id',
        ),
    ]
