# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-13 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_perm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermrelation',
            name='perm_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
